version: '3.2'

services:
  airflow:
    build: .
    image: clowler:latest
    command: "echo 1"

  airflow_web:
    image: clowler:latest
    env_file:
      - .env
    volumes:
      - ./requirements.txt /app/requirements.txt
      - ./airflow:/app/airflow
      - ./airflow.cfg:/app/airflow/airflow.cfg
      - ./entrypoint:/entrypoint
      - ./dags:/dags
      - ./keys:/keys
    networks:
      - airflow_net
    ports:
      - target: 8080
        published: ${WEB_PORT}
    depends_on:
      - airflow_db
      - airflow_redis
    entrypoint: /entrypoint/web.sh


  airflow_scheduler:
    image: clowler:latest
    env_file:
      - .env
    volumes:
      - ./requirements.txt /app/requirements.txt
      - ./airflow:/app/airflow
      - ./airflow.cfg:/app/airflow/airflow.cfg
      - ./entrypoint:/entrypoint
      - ./dags:/dags
      - ./keys:/keys
    networks:
      - airflow_net
    ports:
      - target: 8081
        published: ${FLOWER_PORT}
    depends_on:
      - airflow_web
      - airflow_db
      - airflow_redis
    entrypoint: /entrypoint/scheduler.sh

  airflow_db:
    image: postgres:10
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PASSWORD=airflow
    networks:
      - airflow_net
    ports:
      - target: 5432
        published: ${AIRFLOW_DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  airflow_redis:
    image: redis:5
    networks:
      - airflow_net
    ports:
      - target: 6379
        published: ${AIRFLOW_REDIS_PORT}

volumes:
  db_data:

networks:
  airflow_net:
