version: '3.2'

services:
  airflow:
    build: .
    image: clowler:latest

  airlow_web:
    image: clowler:latest
    volumes:
      - ./airflow:/app/airflow
      - ./src/airflow.cfg:/app/airflow/airflow.cfg
      - ./src/entrypoint:/app/entrypoint
    ports:
      - target: 8080
        published: 8080
    entrypoint: /app/entrypoint/web.sh

  airlow_scheduler:
    image: clowler:latest
    volumes:
      - ./airflow:/app/airflow
      - ./src/airflow.cfg:/app/airflow/airflow.cfg
      - ./src/entrypoint:/app/entrypoint
    entrypoint: /app/entrypoint/scheduler.sh

  airlow_worker:
    image: clowler:latest
    environment:
      - AIRFLOW_HOME=/app/airflow
      - C_FORCE_ROOT=true
    volumes:
      - ./airflow:/app/airflow
      - ./src/airflow.cfg:/app/airflow/airflow.cfg
      - ./src/entrypoint:/app/entrypoint
    entrypoint: /app/entrypoint/worker.sh

  airlow_flower:
    image: clowler:latest
    volumes:
      - ./airflow:/app/airflow
      - ./src/airflow.cfg:/app/airflow/airflow.cfg
      - ./src/entrypoint:/app/entrypoint
    ports:
      - target: 8081
        published: 8081
    entrypoint: /app/entrypoint/flower.sh

  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PASSWORD=airflow
    ports:
      - target: 5432
        published: 15432
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5
    ports:
      - target: 6379
        published: 16379

volumes:
  db_data:
